AGENT_PROFILES = [
    {
        "name": "Cursor Agent",
        "mode": "subscription",
        "subscription_name": "Cursor Pro",
        "strengths": ["codebase 편집 루프", "멀티파일 리팩터링", "개발 워크플로우 자동화"],
        "autonomy": 9.0,
        "context_handling": 8.2,
        "reliability": 8.5,
        "complexity_band": (45, 95),
    },
    {
        "name": "Claude Code Agent",
        "mode": "hybrid",
        "subscription_name": "Claude Pro",
        "api_model_name": "Anthropic Claude Haiku 4.5 API",
        "strengths": ["긴 문맥 분석", "설계/리뷰 중심 작업", "요구사항 정제"],
        "autonomy": 8.6,
        "context_handling": 9.2,
        "reliability": 8.4,
        "complexity_band": (40, 95),
    },
    {
        "name": "OpenAI API Agent Stack",
        "mode": "api",
        "api_model_name": "OpenAI GPT-4.1 mini API",
        "strengths": ["함수 호출 중심 자동화", "툴 연계", "대량 요청 처리"],
        "autonomy": 7.8,
        "context_handling": 7.6,
        "reliability": 8.1,
        "complexity_band": (30, 85),
    },
    {
        "name": "Gemini API Agent Stack",
        "mode": "api",
        "api_model_name": "Google Gemini 2.5 Flash API",
        "strengths": ["저비용 대량 처리", "빠른 응답", "고빈도 반복 작업"],
        "autonomy": 7.2,
        "context_handling": 7.4,
        "reliability": 7.8,
        "complexity_band": (20, 75),
    },
    {
        "name": "ChatGPT Plus Agent Workflow",
        "mode": "subscription",
        "subscription_name": "ChatGPT Plus",
        "strengths": ["아이디어-초안-구현 루프", "범용 작업", "학습 곡선 낮음"],
        "autonomy": 7.6,
        "context_handling": 7.9,
        "reliability": 8.0,
        "complexity_band": (25, 80),
    },
]
